import emails
import vidbot
import subprocess

isms = [
  "abstract expressionism",
    "academic",
    "action painting",
    "aestheticism",
    "art deco",
    "art nouveau",
    "avant-garde",
    "barbizon school",
    "baroque",
    "bauhaus",
    "biedermeier",
    "caravaggisti",
    "carolingian",
    "classicism",
    "cloisonnism",
    "cobra",
    "color field painting",
    "conceptual art",
    "cubism",
    "cubo-futurism",
    "dada",
    "dadaism",
    "de stijl",
    "deformalism",
    "der blaue reiter",
    "die brücke",
    "divisionism",
    "eclecticism",
    "ego-futurism",
    "existentialism",
    "expressionism",
    "fauvism",
    "fluxus",
    "formalism",
    "futurism",
    "geometric abstraction",
    "gothic art",
    "gründerzeit",
    "hard-edge painting",
    "historicism",
    "hudson river school",
    "humanism",
    "hyperrealism",
    "idealism",
    "illusionism",
    "immagine&poesia",
    "impressionism",
    "incoherents",
    "installation art",
    "international gothic",
    "intervention art",
    "jugendstil",
    "kinetic art",
    "land art",
    "les nabis",
    "lettrism",
    "lowbrow",
    "luminism",
    "lyrical abstraction",
    "mail art",
    "manierism",
    "mannerism",
    "maximalism",
    "merovingian",
    "metaphysical art ",
    "minimalism",
    "modern art",
    "modernism",
    "monumentalism",
    "multiculturalism",
    "naturalism",
    "neo-classicism",
    "neo-dada",
    "neo-expressionism",
    "neo-fauvism",
    "neo-geo",
    "neo-impressionism",
    "neo-minimalism",
    "neoclassicism",
    "neoism",
    "neue slowenische kunst",
    "new media art",
    "new objectivity",
    "nonconformism",
    "nouveau realisme",
    "op art",
    "orphism",
    "ottonian",
    "outsider art",
    "performance art",
    "perspectivism",
    "photorealism",
    "pointilism",
    "pop art",
    "post-conceptualism",
    "post-impressionism",
    "post-minimalism",
    "post-painterly abstraction",
    "post-structuralism",
    "postminimalism",
    "postmodern art",
    "postmodernism",
    "pre-raphaelites",
    "precisionism",
    "primitivism",
    "purism",
    "rayonism",
    "realism",
    "relational art",
    "remodernism",
    "renaissance",
    "rococo",
    "romanesque",
    "romanticism",
    "russian futurism",
    "russian symbolism",
    "scuola romana",
    "secularism",
    "situationist international",
    "social realism",
    "socialist realism",
    "sound art",
    "street art",
    "structuralism",
    "stuckism international",
    "stuckism",
    "superflat",
    "superstroke",
    "suprematism",
    "surrealism",
    "symbolism",
    "synchromism",
    "synthetism",
    "systems art",
    "tachism",
    "tachisme",
    "tonalism",
    "video art",
    "video game art",
    "vorticism",
    "young british artists"
]


# Create our message object 
message = emails.html(
  html="Hello friend!", 
  subject="Specter blah blah", 
  mail_from=("Scrap Ism", "scrapism.sfpc@gmail.com")
)
# Turn into a gif
subprocess.call(["ffmpeg", "-i", "sunset_words.mp4", "sunset_words.gif"])
# Attach the file
# Read the video file in binary form (using rb mode)
message.attach(data=open("sunset_words.gif", "rb"), filename="sunset_words.gif")

# Send the email
message.send(
  to=("Sam", "splavigne@gmail.com"), 
  # A bunch of email server stuff from google
  smtp={
    "host": "smtp.gmail.com",
    "port": 465,
    "ssl": True,
    # You'd use an actual email login info (maybe not your own)
    "user": "scrapism.sfpc@gmail.com",
    "password": "scrapismscrapism"
  }
)
